#!/usr/bin/env ruby
# -*- encoding: sjis -*-
require 'nkf'
require 'open3'

BLOCK_SIZE     = 1048576
NKF_TO_WINDOWS = "--sjis"
SHOW_ANOTHER_WINDOW = ["netsh", "nslookup", "cmd" ]

PATH = %W(
    /cygdrive/c/Android/android-sdk/tools
    /cygdrive/c/Android/android-sdk/platform-tools
    /cygdrive/c/Program\ Files/Oracle/VirtualBox/
    /cygdrive/c/Program\ Files/Aspell/bin/
    /cygdrive/c/Program\ Files/ruby-1.8/bin/
  )

def main
  setup_path_environment

  $option = Hash.new false
  if File.basename($0) == "cygsmart" then
    $option = consume
    wincmd = ARGV.shift
  else
    wincmd = File.basename($0)
  end

  cmdline = compose_commandline wincmd, ARGV

  if cmdline.include?("cygstart") then
    system(cmdline)
    exit
  end
  execute cmdline
end

def setup_path_environment
  self_filename = File.expand_path(File.dirname(__FILE__))

  ENV["PATH"] = PATH.inject(ENV["PATH"]) do |memo, path|
    memo + ":" + path
  end
end

def consume
  option = Hash.new false

  arg = ARGV.first
  return option if arg[0, 1] != "-"

  ARGV.shift

  arg[1..-1].each_char do |char|
    case char
    when "c"
      option["/c"] = true
    when "k"
      option["/k"] = true
    when "r"
      option["raw"] = true
    end
  end

  return option
end

CYGPATH = "/usr/bin/cygpath"
def cygpath_ma filename
  cmd = %x(#{CYGPATH} -ma #{filename}).chomp
  %("#{cmd}")
end

def cygpath_ua filename
  %x(#{CYGPATH} -ua #{filename}).chomp
end

def where filename
  glob = ENV["PATH"].gsub(":",",")
  glob = "{#{glob}}/#{filename}"
  Dir[glob].each do |candidate|
    yield candidate
  end
end

def realexe basename
  %w(.bat .cmd .exe).each do |suffix|
    filename = "#{basename}#{suffix}"

    where(filename) do |candidate|
      if suffix == ".bat" or suffix == ".cmd" then
        return invoking_command candidate
      end
      filetype = %x(/usr/bin/file #{candidate})
      if filetype.include?("Windows") or
        filetype.include?("MS DOS") then
        ldd = %x(/usr/bin/ldd #{candidate})
        next if ldd.include?("cygwin1.dll")
        return invoking_command candidate
      end
    end
  end
end

def invoking_command filename
  winexe = cygpath_ma filename
  cmd = cygpath_ua "$COMSPEC"
  if $option["/c"] then
    return %(/usr/bin/cygstart #{cmd} /c #{winexe})
  elsif $option["/k"] then
    return %(/usr/bin/cygstart #{cmd} /k #{winexe})
  else
    return "\"#{winexe}\""
  end
end

def compose_commandline wincmd, argv
  case wincmd
  when *SHOW_ANOTHER_WINDOW
    if wincmd == "cmd" then
      $option["/c"] = true
    else
      $option["/k"] = true
    end
  end

  arguments = [realexe wincmd]

  if $option["raw"] then
    return argv.join(" ")
  end

  until argv.empty?
    argument = argv.shift
    case argument
    when "--"
      arguments << argv.shift
    when /^-/
      arguments << argument
    when %r(^/)
      if File.file? argument then
        arguments << cygpath_wa(argument)
      else
        arguments << argument
      end
    else
      if argument.include?("/") and
        not argument.include?(":") then
        arguments << cygpath_wa(argument)
      else
        arguments << argument
      end
    end
  end

  return arguments.join(" ")
end

def execute cmdline
  Open3.popen3(cmdline) do |stdin, stdout, stderr, wait_thr|
    loop do
      begin
        convert stdin, stdout, stderr
      rescue Errno::EAGAIN => e
        next
      rescue EOFError => e
        break
      ensure
        sleep 0.1
      end
    end
  end
end

def convert stdin, stdout, stderr
  rs, = IO.select([stdout, stderr, $stdin], nil, nil, 1)
  return if rs.nil?
  rs.each do |r|
    buffer = r.read_nonblock(BLOCK_SIZE)
    if r == stdout then
      $stdout.write NKF.nkf("--utf8 -Lu", buffer)
    elsif r == stderr then
      $stderr.write NKF.nkf("--utf8 -Lu", buffer)
    elsif r == $stdin then
      stdin.write NKF.nkf(NKF_TO_WINDOWS, $stdin.read_nonblock(BLOCK_SIZE))
    else
      raise "unexpected"
    end
  end
end

if $0 == __FILE__ then
  main
end

